#!/usr/bin/env python
# OpenShift Quickstarter
# Deploy a variety of applications to the cloud with a single command.
#
# Copyright (C) 2011 Red Hat, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Author: Luke Macken <lmacken@redhat.com>

import sys, subprocess

python = 'wsgi-3.2'
perl = 'perl-5.10'
java = 'jbossas-7.0'
ruby = 'rack-1.1'
php = 'php-5.3'

db = 'mysql-5.1'

openshift_repo = 'git://github.com/openshift/%s-example.git'
openshift_alt_repo = 'git://github.com/openshift/%s-openshift-quickstart.git'
lmacken_repo = 'git://github.com/lmacken/%s-openshift-quickstart.git'
lmacken_fork_repo = 'git://github.com/lmacken/%s-example.git'

quickstarts = {
    'pyramid': {'type': python, 'db': True, 'repo': lmacken_repo },
    'turbogears2': {'type': python, 'db': True, 'repo': lmacken_repo},
    'django': {'type': python, 'db': True, 'repo': lmacken_fork_repo},
    'pyblosxom': {'type': python, 'db': False, 'repo': lmacken_repo},
    'rails': {'type': ruby, 'db': True, 'repo': openshift_repo},
    'reviewboard': {'type': python, 'db': True, 'repo': openshift_repo},
    'mediawiki': {'type': php, 'db': True, 'repo': openshift_repo},
    'drupal': {'type': php, 'db': True, 'repo': openshift_repo},
    'wordpress': {'type': php, 'db': True, 'repo': openshift_repo},
    'cakephp': {'type': php, 'db': True, 'repo': openshift_repo},
    'wolfcms': {'type': php, 'db': True, 'repo': openshift_repo},
    'frogcms': {'type': php, 'db': True, 'repo': openshift_repo},
    'seambooking': {'type': java, 'db': True, 'repo': openshift_repo},
    'sqlbuddy': {'type': php, 'db': True, 'repo': openshift_alt_repo},
}

run = lambda cmd, **kw: subprocess.call(cmd, shell=True, **kw)

if len(sys.argv) != 5:
    print(file('README.md').read())
    sys.exit(1)

prog, login, domain, app_name, quickstart = sys.argv

# Create the application & database
app = quickstarts[quickstart]
run('rhc-create-app -a %s -t %s -l %s' % (app_name, app['type'], login))
if app['db']:
    print("Adding %s cartridge to %s" % (db, app_name))
    run('rhc-ctl-app -a %s -e add-%s -l %s' % (app_name, db, login))

# Pull in the appropriate quickstart template
run('git remote add upstream -m master %s' % app['repo'] % quickstart,
    cwd=app_name)
run('git pull -s recursive -X theirs upstream master', cwd=app_name)

# Pre-deployment configuration
if app in ('frogcms', 'wolfcms'):
    run('sed -i -e "s/%s-dbvs/%s-%s/" php/config.php' % (
        quickstart, app_name, domain), cwd=app_name)
    run('git commit -am "Update the base URL"', cwd=app_name)

# Push our code to the cloud
run('git push', cwd=app_name)

print("Complete!")
print("You can view your application at http://%s-%s.rhcloud.com" % (
      app_name, domain))
